version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    env_file:
      - backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app

  frontend:
    build: ./frontend
    ports:
      - "0.0.0.0:3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
    environment:
      - NODE_ENV=development

volumes:
  postgres_data: