version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=stratix
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stratix-network

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env.production
    networks:
      - stratix-network
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/stratix
    networks:
      - stratix-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - stratix-network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

networks:
  stratix-network:
    driver: bridge

volumes:
  postgres_data: