"""add is_admin nullable

Revision ID: 06f3a8d1567e
Revises: 49b4741dac9d
Create Date: 2025-09-29 11:45:03.126273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f3a8d1567e'
down_revision: Union[str, Sequence[str], None] = '49b4741dac9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'is_admin')
    # ### end Alembic commands ###
